### ISSUE TITLE
Configuration Validation

### ISSUE THREAD

**Issue by nsgoding** [richibrics/HassMonitorMqtt#1]
I get this error  Invalid config for [monitor_mqtt]: expected a dictionary for dictionary value @ data['monitor_mqtt']. Got [OrderedDict([('client_name', 'PcName1')]), OrderedDict([('client_name', 'PcName2')])].  When I check my configuration.

Thanks

**Comment by matthewc95** [comment]
> I get this error Invalid config for [monitor_mqtt]: expected a dictionary for dictionary value @ data['monitor_mqtt']. Got [OrderedDict([('client_name', 'PcName1')]), OrderedDict([('client_name', 'PcName2')])]. When I check my configuration.
> 
> Thanks

Same, thanks

**Comment by richibrics** [comment]
Yes sorry, configuration sample in README was wrong. Check now
