### ISSUE TITLE
some sensors unavailble

### ISSUE THREAD

**Issue by AlexKash500** [richibrics/HassMonitorMqtt#3]
some sensors unavailble
as I can understood there is problem with subtopic in MQTT. for example cpu/cpu-percantage
![image](https://user-images.githubusercontent.com/69472472/98685582-96eb9000-2378-11eb-9e0c-513369d56110.png)

**Comment by richibrics** [comment]
Yes, I'm solving these old topic problems

**Comment by richibrics** [comment]
Check, should have solved now

**Comment by richibrics** [comment]
Reopen if you have other problems
